version: "3"

# docker-compose requires the x- prefix for unrelated nodes
x-zeek-template: &ZEEK_BASE
  build: ./zeek
  image: ckreibich/zeek
  environment:
    ZEEK_DEFAULT_LISTEN_ADDRESS: "0.0.0.0"
  volumes:
    - ./scripts:/tmp/scripts:z

x-zeek-agent: &ZEEK_AGENT
  command: /usr/local/zeek/bin/zeek -j /tmp/scripts/agent.zeek
  ports:
    - "9999"

x-zeek-controller: &ZEEK_CONTROLLER
  command: /usr/local/zeek/bin/zeek -j /tmp/scripts/controller.zeek
  ports:
    - "2150:2150"
  
services:
  controller:
    <<: *ZEEK_BASE
    <<: *ZEEK_CONTROLLER

  inst1:
    <<: *ZEEK_BASE
    <<: *ZEEK_AGENT
    
  inst2:
    <<: *ZEEK_BASE
    <<: *ZEEK_AGENT

  client:
    build: ./zeek-client
    image: ckreibich/zeek-client
    tty: true
